### ISSUE TITLE
Front End Development Courses to be Completed

### ISSUE THREAD

**Issue by DesignerNW** [DesignerNW/Treehouse#2]
## TODO

*Courses left to complete the Treehouse Front End Track*

* [ ] Debugging CSS/Chrome Dev Tools
* [ ] Responsive Layouts
* [ ] Practice Media Queries
* [ ] CSS Flexbot
* [ ] HTML Forms
* [ ] Variables
* [ ] JavaScript Number
* [ ] JavaScript Functions
* [ ] JavaScript Loops, Arrays...
* [ ] CSS Selectors
* [ ] Web Accessibility Compliance
* [ ] Web Optimization

:tada: :ok_woman: :confetti_ball:
